### ISSUE TITLE
PHP Warning: Undefined array key "btc"

### ISSUE THREAD

**Issue by guymass** [btcpayserver/opencart#9] opened 2023-02-26 20:36 UTC
I have installed the extension from the marketplace on my OpenCart 4 website and configured it as the only default enabled currency, how ever I see this error when ever I try to safe the bitcoin in the currency list.

PHP Warning: Undefined array key "btc"
File: /var/www/html/opencart/extension/opencart/admin/controller/currency/ecb.php
Line: 103

My Bitcoin configuration look like this:

![Screen Shot 5783-06-05 at 19 21 06](https://user-images.githubusercontent.com/58882903/221435714-38a95beb-2b07-45bb-b83b-fb7f10c831c6.jpg)

It seems there is not ISO currency code for Bitcoin, maybe that is the problem. How can I overcome this problem so that my OpenCart will use my BTCPAY server store and display prices on product in bitcoin?

Can anyone here please help sort this out?

**Comment by IP-CAM** [comment] 2023-02-27 09:25
Better read here before wasting more time on this:
https://forum.opencart.com/viewtopic.php?t=230557#p852891

**Comment by ndeet** [comment] 2023-02-27 13:08
@IP-CAM lol wtf, they relase a new major version but months after the release they still consider it to be not used for production? holy moly I have no words 

@guymass thanks for the report, it looks like a problem with currency conversion (ecb.php). I will try to reproduce and debug and let you know if I can fix it from within the plugin.

**Comment by IP-CAM** [comment] 2023-02-27 13:57
Well, The OC Fellow is getting old, and his latest Version Release is already define('VERSION', '4.0.2.0')
https://github.com/opencart/opencart
but those, familiar with OC, already know, that it's always taking a while, until a new Release can be used. In addition to this, many former Dev's don't seem to care much about his doings, and this will delay things additionally. In addition to the Fact, that not many tested Extensions exist for the latest Versions either. But everybody is free, to either jump onto the latest Bandwagon, or then use something, already known to work, like the define('VERSION', '3.0.3.9')
https://github.com/opencart/opencart-3
Good Luck !

**Comment by ndeet** [comment] 2023-02-27 14:14
@IP-CAM yes, but I assumed it was considered stable as it seems OC4 was in the works for some years, silly me :D

The [opencart-3 repo](https://github.com/opencart/opencart-3) you linked does not seem to have a 3.0.3.9 release, and there is no official one, it seems 3.0.3.x changes get all merged/committed into the main branch and no new releases. Also there is a 3.x maintenance branch on the main repo which gets updates https://github.com/opencart/opencart/commits/3.0.x.x_Maintenance but which seems to differ from the one linked by you. Looks a bit messy out there :D

@guymass I tried to reproduce but it works for me. I setup an additional currency BTC and with the same settings like you. On frontend I switch to BTC and the checkout works. Can you give more details about your setup, is BTC the only and default language you use? Does the checkout work? A PHP "warning" does not break the site so it could be that everything works while showing the error. Please give more details.

**Comment by ndeet** [comment] 2023-02-27 14:19
@guymass here are my store -> local settings, you should disable the automatic currency converter too but as said, even with a warning there should be no problem, as long as you get redirected to BTCPay checkout, all is good.
![image](https://user-images.githubusercontent.com/1136761/221587756-ef443822-89e6-4500-8917-94ff3341c2e9.png)

**Comment by ndeet** [comment] 2023-02-27 14:46
Also Bitcoin has 8 decimals (not 2). You should change that in your currency config.

**Comment by guymass** [comment] 2023-02-27 15:55
I have set 8 decimals, disabled auto update currency but I still see that error. I am not sure about the checkout yet still haven't got to testing it, hope to do it this week.

In my case I am running a Ubuntu VM behind a reverse ssh tunnel to my proxy server which is handling the redirects and SSL. Locally I am running the docker version without nginx set as a proxy. This is my site in case someone want to check it out.

https://btc.alive528.com

**Comment by ndeet** [comment] 2023-02-27 16:00
Ok then we can maybe close this issue. It seems to be related to the backend of opencart core only and only when you save the currency which is not related to our plugin. Also I saw you also opened an issue over there https://github.com/opencart/opencart/issues/12192

Like I said, it is a warning and does not affect the checkout functionality at all it seems. It will be fixed in OC4 at some point to avoid the warning but you should be good to go.

**Closed as completed by ndeet** 2023-02-27 16:00 UTC

**Comment by guymass** [comment] 2023-02-27 16:02
Much thanks for the help, god bless!

**Comment by IP-CAM** [comment] 2023-02-27 16:04
#Looks a bit messy out there
It is, the Maintenance likely includes all the PHP v.8.x Updates, and the v.3.0.3.9 is more a 'private' Release. But I am not sure about this. Whatever, I would try both of them, to find out, if you care, to get the best of them. One reason for me, to still use v.1.5.6.5 :)
Good Luck !

**Comment by guymass** [comment] 2023-02-27 16:06
I forgot to mention one more thing. Because I cannot save the currency properly the price on my product still shows USD and I cannot get it to display bitcoin. In any case this is a new server so I can wait for a solution there's no rush.
![Screen Shot 5783-06-06 at 18 04 42](https://user-images.githubusercontent.com/58882903/221615939-ec01963f-86b8-4575-8597-dc0fbfb95f25.jpg)
